#!/usr/bin/env bash
# subdomain

datos () {
    linea=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $linea" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  datos "$1" "www"
  datos "$1" "lb-01"
  datos "$1" "web-01"
  datos "$1" "web-02"
elif [ "$#" == 2 ]
then
  datos "$1" "$2"
fi