#!/usr/bin/env bash
#install nginx in server
sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R "$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/ a\ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart

sudo service nginx reload
