#!/usr/bin/env bash
#script that gives you information about the school file.
directories="$(find . -name school)"
if [ "$directories" = "./school" ]
then
   echo "school file exists"
	if [ -s "$directories" ]
	then
	   echo "school file is not empty"
	else
	   echo	"school file is empty"
	fi
	if [ -f "$directories" ]
	then
	   echo "school is a regular file"
	fi
else
echo "school file does not exist"
fi

